import Link from 'next/link'
import { ArrowLeft } from 'lucide-react'

export const metadata = {
  title: 'Terms of Service | Reveald',
}

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-bg-primary">
      <div className="max-w-2xl mx-auto px-section py-8">
        <Link
          href="/"
          className="flex items-center gap-2 text-body text-text-secondary hover:text-text-primary transition-colors min-h-[44px] mb-6"
        >
          <ArrowLeft size={18} strokeWidth={1.5} />
          Back
        </Link>

        <h1 className="font-serif text-display text-text-primary mb-8">Terms of Service</h1>

        <div className="flex flex-col gap-6 text-body text-text-secondary leading-relaxed">
          <p><strong className="text-text-primary">Last updated:</strong> February 2026</p>

          <section className="flex flex-col gap-3">
            <h2 className="text-subtitle text-text-primary">1. Acceptance of Terms</h2>
            <p>
              By using Reveald, you agree to these Terms of Service. If you do not agree, please do not use the service.
            </p>
          </section>

          <section className="flex flex-col gap-3">
            <h2 className="text-subtitle text-text-primary">2. Description of Service</h2>
            <p>
              Reveald is an AI-powered conversation analysis tool. It provides interpretations of conversations for informational and entertainment purposes. The analyses are generated by artificial intelligence and should not be treated as professional psychological, legal, or medical advice.
            </p>
          </section>

          <section className="flex flex-col gap-3">
            <h2 className="text-subtitle text-text-primary">3. User Accounts</h2>
            <p>
              You must create an account to use Reveald. You are responsible for maintaining the security of your account credentials. You must provide accurate information when creating your account.
            </p>
          </section>

          <section className="flex flex-col gap-3">
            <h2 className="text-subtitle text-text-primary">4. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="flex flex-col gap-2 list-disc pl-5">
              <li>Use Reveald for harassment, stalking, or any illegal purpose.</li>
              <li>Submit conversations without the knowledge or consent of the participants, where required by law.</li>
              <li>Attempt to reverse-engineer, abuse, or overload the service.</li>
              <li>Share your account credentials with others.</li>
            </ul>
          </section>

          <section className="flex flex-col gap-3">
            <h2 className="text-subtitle text-text-primary">5. Subscriptions and Payments</h2>
            <p>
              Reveald offers free and paid plans. Paid subscriptions are billed monthly or annually through Stripe. You may cancel at any time; your plan remains active until the end of the current billing period. Purchased credit packs do not expire.
            </p>
          </section>

          <section className="flex flex-col gap-3">
            <h2 className="text-subtitle text-text-primary">6. Refunds</h2>
            <p>
              Subscription charges are non-refundable except where required by law. If you experience a technical issue that prevents you from using the service, contact us and we will work to resolve it.
            </p>
          </section>

          <section className="flex flex-col gap-3">
            <h2 className="text-subtitle text-text-primary">7. Disclaimer</h2>
            <p>
              Reveald provides AI-generated analysis for informational purposes only. We make no guarantees about the accuracy, completeness, or reliability of the analyses. The service is provided "as is" without warranties of any kind.
            </p>
          </section>

          <section className="flex flex-col gap-3">
            <h2 className="text-subtitle text-text-primary">8. Limitation of Liability</h2>
            <p>
              Reveald shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of the service, including but not limited to decisions made based on the analyses provided.
            </p>
          </section>

          <section className="flex flex-col gap-3">
            <h2 className="text-subtitle text-text-primary">9. Changes to Terms</h2>
            <p>
              We may update these terms from time to time. Continued use of the service after changes constitutes acceptance of the new terms.
            </p>
          </section>

          <section className="flex flex-col gap-3">
            <h2 className="text-subtitle text-text-primary">10. Contact</h2>
            <p>
              If you have questions about these terms, please contact us at legal@reveald.app.
            </p>
          </section>
        </div>
      </div>
    </main>
  )
}
